export const questions=[
{id:'role',group:'Seu contexto',title:'Qual é seu papel nas decisões da empresa?',options:[['owner','Sou dono(a) ou sócio(a) decisor(a)'],['decision','Participo da decisão'],['team','Atuo na equipe, sem participar da decisão']]},
{id:'maturity',group:'Seu contexto',title:'Em que momento está a empresa?',options:[['validated','Já temos produto, operação e vendas validados'],['building','Ainda estamos validando produto, operação ou vendas']]},
{id:'monthly',group:'Seu contexto',title:'Qual faixa representa seu faturamento mensal?',help:'As faixas abaixo seguem a régua de Ed. Se seu valor cair em uma lacuna, avance pela opção de esclarecimento, sem escolher uma faixa aproximada.',options:[['low','Até 29 mil/mês'],['mid','De 30 a 99 mil/mês'],['high','De 100 mil a 499 mil/mês'],['top','Acima de 500 mil/mês'],['validation','Estou em fase de validação, ainda sem faturamento']],clarify:true},
{id:'annual',group:'Seu contexto',title:'Seu faturamento nos últimos 12 meses atingiu R$1 milhão?',help:'Não estimamos o anual multiplicando o mês atual. Esta resposta permite avaliar o critério anual separadamente.',options:[['yes','Sim, R$1 milhão ou mais'],['no','Não, ficou abaixo de R$1 milhão'],['unknown','Não sei informar']]},
{id:'model',group:'Seu contexto',title:'Qual é o principal modelo do negócio?',options:[['services','Serviços ou consultoria'],['commerce','Comércio ou e-commerce'],['industry','Indústria'],['digital','Produtos digitais ou educação'],['subscription','Assinatura ou software'],['other','Outro modelo']]},
{id:'acquisition',group:'Sistema de Aquisição',title:'Você consegue prever de onde virão as próximas vendas?',options:[['strong','Sim. Acompanhamos canais, oportunidades e conversão'],['partial','Em parte. Há canais funcionando, mas oscilamos'],['weak','Não. Dependemos de ações pontuais ou indicação'],['unknown','Não tenho dados para responder']]},
{id:'products',group:'Sistema de Produtos',title:'Existe um caminho claro para a próxima compra?',options:[['strong','Sim. Temos ofertas conectadas e acompanhamos a evolução'],['partial','Temos outras ofertas, mas a passagem não é consistente'],['weak','Não. A venda termina na primeira oferta'],['unknown','Não tenho dados para responder']]},
{id:'margin',group:'Sistema de Margem e LTV',title:'Você conhece a margem de contribuição das principais ofertas?',help:'Receita menos custos e despesas variáveis associados à venda. Saber o faturamento não basta.',options:[['strong','Sim. Atualizamos e usamos esse dado nas decisões'],['partial','Temos estimativas, mas sem revisão consistente'],['weak','Não apuramos a margem por oferta'],['unknown','Não sei como isso é acompanhado']]},
{id:'retention',group:'Sistema de Margem e LTV',title:'Como você acompanha recompra ou recorrência?',options:[['strong','Medimos retorno e temos um processo ativo de continuidade'],['partial','Há retorno, mas o acompanhamento é irregular'],['weak','Não há processo de continuidade ou indicação estruturada'],['unknown','Ainda não sabemos ou não avaliamos a aplicação ao modelo']]},
{id:'dependency',group:'Capacidade de execução',title:'Quanto a operação depende de você?',options:[['independent','A equipe opera com processos e autonomia'],['shared','Algumas decisões ainda ficam concentradas'],['dependent','Sem mim, vendas ou entrega param'],['unknown','Não sei avaliar']]},
{id:'pain',group:'Sua prioridade',title:'O que mais exige atenção neste momento?',options:[['acquisition','Previsibilidade de vendas'],['products','Esteira e evolução das ofertas'],['margin','Margem, recompra ou recorrência'],['owner','Dependência do dono'],['none','Não identifico uma dor nessas áreas']]},
{id:'timing',group:'Sua prioridade',title:'Quando pretende agir sobre essa prioridade?',options:[['30','Nos próximos 30 dias'],['90','Entre 31 e 90 dias'],['later','Depois de 90 dias'],['unknown','Ainda não defini']]},
{id:'conversation',group:'Próximo passo',title:'Você teria interesse em conversar sobre essa leitura?',help:'Esta resposta não agenda uma conversa nem envia seus dados. A integração está pendente neste preview.',options:[['yes','Sim, tenho interesse'],['no','Prefiro começar pelo relatório']]}
];
